export const PINK_ROOM = 'pink-room'; //true
export const OUTLAW_HEADQUARTERS = 'outlaw-headquarters'; // done
export const DRUG_DEN = 'drug-den'; //done
export const MEETING_HALL = 'meeting-hall'; //done
export const SINGLE_FIRE = 'single-fire'; //done
export const SUMMONING_CIRCLE = 'summoning-circle'; //done
export const MANNEQUINN_ROOM = 'mannequinn_room'; //done
export const GOBLIN_LAIR = 'goblin-lair'; //done
export const SLIME_ROOM = 'slime-room'; //done
export const COFFIN_ROOM = 'coffin-room';//done
export const RICE_CHALLENGE = 'rice-challenge'; //done
export const CREEPY_CORRIDOR = 'creepy-corridor'; //done
export const ABANDONED_KITCHEN = 'abandoned-kitchen'; //done
export const MEDITATION_ROOM = 'meditiation-room'; //done
export const SPIDER_DEN = 'spider-den'; //done
export const SNAKE_PIT = 'snake-pit'; //done
export const FIRST_ALTAR = 'first-altar'; //done
export const SECOND_ALTAR = 'second-altar'; //done
export const THIRD_ALTER = 'third-altar';//done
export const FOURTH_ALTER = 'fourth-altar';
export const CENTER_ROOM = 'center-room'; //done

export const CODE1 = 'ry3uhc'; //swift - altar 1
export const CODE2 = 'er8em5'; //Luna - altar 2
export const CODE3 = '4r7zwa'; //nervath - altar 3
export const CODE4 = 'r8crib';
export const CODE5 = '43qp6w'; //zuk - altar 1